### ISSUE TITLE
Support external sns event

### ISSUE THREAD

**Issue by alexef** [silvermine/serverless-plugin-external-sns-events#1]
Hello,

My function runs in my account in the `eu-central-1` region, but needs to subscribe to an event in another account, in the `us-east-1` region: `arn:aws:sns:us-east-1:806199016981:AmazonIpSpaceChanged`.

I'm getting:

```
Serverless: Need to subscribe cfsg-sandbox-default to arn:aws:sns:us-east-1:806199016981:AmazonIpSpaceChanged

  Config Error -------------------------------------------

     Missing region in config

     For debugging logs, run again after setting SLS_DEBUG env var.

  Stack Trace --------------------------------------------

ConfigError: Missing region in config
    at Request.VALIDATE_REGION (/usr/local/lib/node_modules/aws-sdk/lib/event_listeners.js:81:45)
    at Request.callListeners (/usr/local/lib/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at callNextListener (/usr/local/lib/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at /usr/local/lib/node_modules/aws-sdk/lib/event_listeners.js:75:9
    at finish (/usr/local/lib/node_modules/aws-sdk/lib/config.js:307:7)
    at /usr/local/lib/node_modules/aws-sdk/lib/config.js:323:9
    at SharedIniFileCredentials.get (/usr/local/lib/node_modules/aws-sdk/lib/credentials.js:126:7)
    at getAsyncCredentials (/usr/local/lib/node_modules/aws-sdk/lib/config.js:317:24)
    at Config.getCredentials (/usr/local/lib/node_modules/aws-sdk/lib/config.js:337:9)
    at Request.VALIDATE_CREDENTIALS (/usr/local/lib/node_modules/aws-sdk/lib/event_listeners.js:70:26)
    at Request.callListeners (/usr/local/lib/node_modules/aws-sdk/lib/sequential_executor.js:101:18)
    at Request.emit (/usr/local/lib/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/lib/node_modules/aws-sdk/lib/request.js:668:14)
    at Request.transition (/usr/local/lib/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at Request.runTo (/usr/local/lib/node_modules/aws-sdk/lib/request.js:394:15)
```

and by inspecting the code, it looks like this is not supported right now. Can you please add it to your plugin? I don't know enough js to write the PR myself.

**Comment by jthomerson** [comment]
No longer needed since serverless by default supports ARN subscriptions.

**Comment by jthomerson** [comment]
Oh, I meant the cross-account part was no longer needed. See https://github.com/serverless/serverless/issues/3676 for a discussion of the cross-region portion of this.
