### ISSUE TITLE
Config Error:  Missing region in config

### ISSUE THREAD

**Issue by gmetzker** [silvermine/serverless-plugin-external-sns-events#7]
I'm was trying to use the plugin but I get an error that there is 'Missing region in config' I think this is coming from aws-sdk.  Is there anything I need to do to when setting up the the plugin to force it to inherit the region from serverless?  

In my `serverless.yml` I am explicitly setting the region.

```
Serverless: Need to subscribe glmhello-dev to glm-topic
 
  Config Error -------------------------------------------
 
     Missing region in config
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
ConfigError: Missing region in config
    at Request.VALIDATE_REGION (/Users/gmetzker/glm-lambda/node_modules/aws-sdk/lib/event_listeners.js:81:45)
    at Request.callListeners (/Users/gmetzker/glm-lambda/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at callNextListener (/Users/gmetzker/glm-lambda/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at /Users/gmetzker/glm-lambda/node_modules/aws-sdk/lib/event_listeners.js:75:9
    at finish (/Users/gmetzker/glm-lambda/node_modules/aws-sdk/lib/config.js:308:7)
    at /Users/gmetzker/glm-lambda/node_modules/aws-sdk/lib/config.js:324:9
    at SharedIniFileCredentials.get (/Users/gmetzker/glm-lambda/node_modules/aws-sdk/lib/credentials.js:126:7)
    at getAsyncCredentials (/Users/gmetzker/glm-lambda/node_modules/aws-sdk/lib/config.js:318:24)
    at Config.getCredentials (/Users/gmetzker/glm-lambda/node_modules/aws-sdk/lib/config.js:338:9)
    at Request.VALIDATE_CREDENTIALS (/Users/gmetzker/glm-lambda/node_modules/aws-sdk/lib/event_listeners.js:70:26)
    at Request.callListeners (/Users/gmetzker/glm-lambda/node_modules/aws-sdk/lib/sequential_executor.js:101:18)
    at Request.emit (/Users/gmetzker/glm-lambda/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/gmetzker/glm-lambda/node_modules/aws-sdk/lib/request.js:668:14)
    at Request.transition (/Users/gmetzker/glm-lambda/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/gmetzker/glm-lambda/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at Request.runTo (/Users/gmetzker/glm-lambda/node_modules/aws-sdk/lib/request.js:394:15)
```

**My package.json to install the plugin**

```
{
  "name": "glm-lambda-test",
  "version": "1.0.0",
  "description": "Serverless install requirements",
  "dependencies": {
    "serverless-plugin-external-sns-events": "^1.0.0",
    "aws-sdk": "^2.7.13"
  },
  "engines": {
    "node": "7.2.1"
  }
}
```

**Comment by jthomerson** [comment]
See #4 - you are missing `AWS_REGION` environment variable, which the SDK requires.

**Comment by gmetzker** [comment]
So I tried that and I get a different error.
```
  Resource Not Found Exception ---------------------------
 
     Function not found: arn:aws:lambda:us-west-2:{some-other-accnt}:function:{function-name}
```
It appears it's trying to use my default aws `acct_id` instead of the account associated with my current AWS profile/credentials.

It looks like the default constructor on the SDK objects is picking up different aws context than the rest of serverless.  Which means it's not using the correct account id or region.

Why not use the built in provider to make AWS sdk calls so the context is the same?  

Other plugins seem to be doing something like this:

```
this.provider = this.serverless.getProvider('aws');
...
this.provider.request(
      'Lambda',
      'getFunction',
       { FunctionName: fnDef.name }
    )
```

**Comment by jthomerson** [comment]
I like your suggestion to use the built-in provider @gmetzker - I had initially tried to find where I could access it and make a call but was on a time constraint, didn't immediately see how, and gave up. Doing that we could also remove the NPM dependency on AWS SDK probably. I'd love a pull request for this.

**Comment by gmetzker** [comment]
Ok.  I'll see if I can work on that.  Thanks J.

**Comment by gmetzker** [comment]
Hi Jeremy,
I think this should be ready to go.  I've added a bunch of unit tests, and in my own direct testing it seems to be working well.  Please pull if you could.

**Comment by Govinda-Fichtner** [comment]
I am running into this problem, too,  when I try to remove a serverless 1.5 service configured with this plugin. Is there an estimated time when the MR will be approved and an update is available via NPM?

**Comment by Govinda-Fichtner** [comment]
@jthomerson It would be really awesome if you could review/merge the PR from @gmetzker
